Document: otfbot
Title: Debian otfbot Manual
Author: <insert document author here>
Abstract: This manual describes what otfbot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/otfbot/otfbot.sgml.gz

Format: postscript
Files: /usr/share/doc/otfbot/otfbot.ps.gz

Format: text
Files: /usr/share/doc/otfbot/otfbot.text.gz

Format: HTML
Index: /usr/share/doc/otfbot/html/index.html
Files: /usr/share/doc/otfbot/html/*.html

  
