#!/usr/bin/python
import sys, re, urllib2

url=urllib2.urlopen("http://localhost:8080/users")
data=url.read()
url.close()

url=urllib2.urlopen("http://localhost:8080/active_users")
data2=url.read()
url.close()

config=False
if len(sys.argv) >= 2 and sys.argv[1]=="config":
    config=True
    print "graph_title IRC Users"
    print "graph_vlabel num. users"
    print "graph_category chat"
    print "graph_scale no"

#TODO: refactor me
for line in data.split("\n"):
    line2=re.sub("[\#-]", "", line)
    line3=re.sub("[\:\#]", "", line)
    if not line2:
        continue
    if not config:
        print line2.replace(".", "_", 1).replace(":", ".value", 1)
    else:
        print re.sub("\.", "_", line3.split(" ")[0]).replace("-", "")+".label", line3.split(" ")[0]
        print re.sub("\.", "_", line3.split(" ")[0]).replace("-", "")+".min", 0

for line in data2.split("\n"):
    line2=re.sub("[\#-]", "", line)
    line3=re.sub("[\:\#]", "", line)
    if not line2:
        continue
    if not config:
        print line2.replace(".", "_", 1).replace(":", "_active.value", 1)
    else:
        print re.sub("\.", "_", line3.split(" ")[0]).replace("-", "")+"_active.label", line3.split(" ")[0]
        print re.sub("\.", "_", line3.split(" ")[0]).replace("-", "")+"_active.min", 0
