#!/usr/bin/python
import sys, re, urllib2

url=urllib2.urlopen("http://localhost:8080/users")
data=url.read()
url.close()

config=False
if len(sys.argv) >= 2 and sys.argv[1]=="config":
    config=True
    print "graph_title IRC Users"
    print "graph_vlabel \"# User\""
    print "graph_category chat"
    print "graph_scale no"

for line in data.split("\n"):
    line2=re.sub("[\#\:-]", "", line)
    if not line2:
        continue
    if not config:
        print line2.replace(".", "", 1)
    else:
        print re.sub("\.", "", line2.split(" ")[0])+".label", line2.split(" ")[0]
        print re.sub("\.", "", line2.split(" ")[0])+".min", 0
